### ISSUE TITLE
I have a question about compare with those algorithms use each frame + controlNet.

### ISSUE THREAD

**Issue by anchoret2009** [CiaraStrawberry/TemporalKit#25]
At first thanks for your contributions.

When I set per side =3 and 5 frames per keyframe, I can not get good result. Because I could not set very Height Resolution, or else the gpu will run out of memory. When I set per side = 2 and 3 frames per keyframe, I could get much better result. If we set side =1 and 1 frame per keyframe, it become to those algorithms to draw each frame with controlNet. My understand is correct or not? But the result you show is much better than those algorithms which can not control the flicker on pictures as you did.

**Comment by CiaraStrawberry** [comment]
Yes it sounds like you have the right idea!

The trick is really trying to get the right balance between frames per keyframe, resolution and sides based on the content, motion and detail in the scene, as you want as many images as possible per plate, without dropping the detail too low or getting smearing due to the time difference between the keyframes.

**Comment by anchoret2009** [comment]
thanks for your reply.

cheers~
