### ISSUE TITLE
The pictures move when I generate a video/images with Batch-Warp, Please help !

### ISSUE THREAD

**Issue by alexfredo** [CiaraStrawberry/TemporalKit#7]
The TemporalKit is awesome but I have a bug when I generate the final video here a example : https://www.veed.io/view/9690d304-7b0c-4a31-bf7a-aca114b8dc3c?panel=share

My settings : 
![settingstemporal](https://user-images.githubusercontent.com/24534698/232484697-c1be93b6-1111-414d-ba9d-d222b2ce95a8.PNG)

**Comment by CiaraStrawberry** [comment]
Hi!
Have you checked the input and output plate resolution sizes are both the same size, a multiple of 8 and a multiple of your per side number (2)?
If you want to diffuse at a lower resolution than you made the plates at, it helps to just regenerate the plates instead of relying on my system accounting for it.

**Comment by alexfredo** [comment]
Ok for example when I generate images input and output the pictures need to be 1296x730 ( multipleof8 x multipleof2 ) ? because my side number is 2 ?

**Comment by CiaraStrawberry** [comment]
Since 730 is only divisible by 2, not 8, you'll probably want to try 1536 as the height with that aspect ( 864, ) will also be divisible by 8 and 2

set 

![image](https://user-images.githubusercontent.com/13116982/232494645-69d249eb-3c38-46d9-b0f5-11f3c71978ff.png)

to 1536 and it should set the plate the correct size based on the input video.

(In retrospect having it default to 1300 is not ideal and i'm gonna change that now.)

**Comment by alexfredo** [comment]
Ok ! the video input can be 1280x720 ? or I need to edit the size ?

**Comment by alexfredo** [comment]
The problem I can't generate plates of 1536x864 because I have only 6gig of vram I tried 768x432 but still the same bug :/

**Comment by alexfredo** [comment]
Oh by enabling low vram of controlnet and adding some commands in the webui-user.bat I can now generate 1536x864 plates

**Comment by CiaraStrawberry** [comment]
ahh i thought i fixed that, pain, can you

a) send me the video you're using that runs into this so i can reproduce

b) just delete the last plate and fill the settings in the batch panel in manually as a workaround.

 768x432 should have worked though, i'd like to give a try on my side then if you could send the video and settings.

**Comment by alexfredo** [comment]
The video test https://easyupload.io/bamk70
The settings : 40fps, batch size 2, resolution 768, side 2, border frame 5, max frame -1

**Comment by alexfredo** [comment]
I tried with controlnet canny, I try with hed now

**Comment by CiaraStrawberry** [comment]
I think the issue is with the number of border frames setting,per side of 2 and a batch size of 2 means there will only be 8 frames per plate, which will mean most of your image is actually from the next plate if you have 5 border frames, which is probably breaking something somewhere due to being an edge case i did not test. 

since the border frames setting means that many frames from the next image get included, but it's also merging for the first border_frames number of frames, there will be more border frames than non border frames.

**Comment by alexfredo** [comment]
Ok what settings do you recommend me ?

**Comment by CiaraStrawberry** [comment]
Probably border settings of 2 or 3, that or you can increase the batch size to 3-4, either should work.

I'm just running some of my own tests for this combination of settings now to double check it'll work for you.

**Comment by alexfredo** [comment]
Ok so batch_size need to be at 3 minimum

**Comment by CiaraStrawberry** [comment]
Exactly, I just pushed a change that will error out if you have a too-large border size from now on too.

**Comment by alexfredo** [comment]
On your test you have put wich number in the border frame ?

**Comment by alexfredo** [comment]
Here the result with 1536x864 generated images and batch_size 3, side 2, border_frame 3, 30fps settings, the images is still unstable : 

https://user-images.githubusercontent.com/24534698/232559242-bf3c6d84-ae2f-414e-92ef-9b4cfe382261.mp4

**Comment by CiaraStrawberry** [comment]
Can you send an example plate that you've made i can look at to check?

**Comment by alexfredo** [comment]
the input and output ?
![input0](https://user-images.githubusercontent.com/24534698/232560734-6284e497-ba83-474d-a766-705735dfcf12.png)
and output
![input0](https://user-images.githubusercontent.com/24534698/232560793-afa3f7a5-350c-4997-a5e5-31c1d014a4b1.png)

**Comment by alexfredo** [comment]
the input and output folder https://easyupload.io/t374w2

**Comment by CiaraStrawberry** [comment]
Perfect, thanks.

I'll check further but i think what's happening is that since you're using so few images per plate, that each plate only lasts about 1/4 of a second, which causes the same flickering effect as you'd typically see if you simply put every frame through sd, maybe you could try using more images per plate, a higher batch size and increase to 60fps?

**Comment by alexfredo** [comment]
I will try, I put few images per plate because I want to have the best resolution possible

**Comment by CiaraStrawberry** [comment]
It's really the knack for getting good outputs with temporal kit is balancing how much resolution you can get with having as few plates as possible so it doesn't jump about.

Checked your files, i'm now 80% sure that's the problem here.

My preferred settings are usually 30 fps, 3 per side, batch size of 5, border 5 and then tweak it depending on how much movement is in the video.

**Comment by alexfredo** [comment]
Ok also I tried a Stabilization AI tool for fix the unstable images it's works pretty well it's not perfect but still better  : 

https://user-images.githubusercontent.com/24534698/232565825-21539a3e-93d0-4bf4-81ee-5b768ecca2d8.mp4

**Comment by CiaraStrawberry** [comment]
Interesting, would be curious how it helps with larger batches.

**Comment by alexfredo** [comment]
I made a test with a Deflicker+Stabilization there's just the transition between scene that is weird ( can be fixed by separate each scenes ) it's allow to keep a high resolution : 

https://user-images.githubusercontent.com/24534698/232580477-ed42b86a-e394-4751-88e2-b143bc018919.mp4

**Comment by alexfredo** [comment]
Also the Stabilization tool seems remove the ghosting but I need to do more test on different scenes  :  
![ghostingtest](https://user-images.githubusercontent.com/24534698/232625829-05bd6116-51c9-4c86-9fcb-7f3ae6f60547.png)

**Comment by alexfredo** [comment]
"would be curious how it helps with larger batches" I tried it's doesn't work well with larger batches, I have good result with the Stabilization only with very few batches.

**Comment by alexfredo** [comment]
I tried the last version of TemporalKit with Batch-Warp no more jump images you fixed the bug! for the ghosting I found a trick maybe it's can help you to understand how to remove it: https://www.reddit.com/r/StableDiffusion/comments/12lmlem/i_found_a_way_to_remove_the_ghosting_of/

**Comment by alexfredo** [comment]
I will try EBsynth but the problem is for make a long video, do you have a easy workflow for make for example a 1 min long video with ebsynth ? thanks

**Comment by alexfredo** [comment]
Also is it possible to adjust the quality of the video ? the video seems little bit compressed, here a test with EBsynth : 

https://user-images.githubusercontent.com/24534698/233869879-f8ecd23a-3669-4bec-b21f-6a50102f1796.mp4

**Comment by CiaraStrawberry** [comment]
I talked about the ebsynth settings in the other window.

I'm gonna at some point implement a segmentation model to cut out the ghosting, aaa so so many things to do.

in terms of the blur, if your output resolution is higher than each plate, aside from manually upscaling each plate yourself, there isn't a ton you can do right now, i'm looking into it.
